apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
  labels:
    app: client-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: client-service:v1
        imagePullPolicy: Never # Для локального використання зібраних образів
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: REDIS_HOST
          value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
